apiVersion: apps/v1
kind: Deployment
metadata:
  name: votes-dpl-producer
  namespace: k8s-votes-namespace
  labels:
    app: producer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: betassaalexandre/producer-votes:latest
        ports:
        - containerPort: 80