apiVersion: apps/v1
kind: Deployment
metadata:
  name: votes-dpl-consumer
  namespace: 
  labels:
    app: consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: betassaalexandre/consumer-votes:latest
        ports:
        - containerPort: 80