apiVersion: v1
kind: Service
metadata:
  name: consumer-service-lb
  namespace: k8s-votes-namespace
spec:
  selector:
    app: consumer
  ports:
   - port: 80
     targetPort: 80
     protocol: TCP
  type: LoadBalancer
